# Generated by Django 4.2.3 on 2023-08-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('f', 'Female'), ('m', 'Male')], help_text='Select your gender', max_length=1, verbose_name='Gender'),
        ),
    ]
