# Generated by Django 4.2.3 on 2023-08-02 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the task.', max_length=250, unique=True, verbose_name='Title')),
                ('description', models.TextField(help_text='Provide a detailed description of the task.', verbose_name='Description')),
                ('start_date', models.DateTimeField(auto_now_add=True, help_text='The date and time when the task was created.', verbose_name='State Date')),
                ('due_date', models.DateTimeField(auto_now=True, help_text='The date and time by which the task should be completed.', verbose_name='Due Date')),
                ('end_date', models.DateTimeField(blank=True, help_text='The date and time when the task was completed.', null=True, verbose_name='End Date')),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('doing', 'Doing'), ('suspend', 'Suspended'), ('done', 'Done')], default='todo', help_text="The current status of the task.          Choose from 'To Do', 'Doing', 'Suspended', or 'Done'.", max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text="The priority level of the task.            Choose from 'Low', 'Medium', or 'High'.", max_length=20, verbose_name='Priority')),
                ('assigned_by', models.ForeignKey(help_text='The user who assigned this task.', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('assigned_to', models.ForeignKey(help_text='The user to whom this task is assigned.', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
            ],
        ),
    ]
