# Generated by Django 4.2.3 on 2023-08-06 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_alter_labeledtask_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeledtask',
            name='label',
            field=models.ForeignKey(help_text='Label to use', on_delete=django.db.models.deletion.CASCADE, to='workspace.label', verbose_name='Label'),
        ),
    ]
